SELECT T.NOM_CCOS, D.COD_EMPL, C.NRO_CONT, B.APE_EMPL, B.NOM_EMPL, C.COD_CARG, K.NOM_CARG, C.FEC_INGR, C.IND_ACTI ESTADO, D.COD_VARI, D.ACT_HORA FECHA_INGRESO_NOVEDAD_KACTUS
from nm_decon D
LEFT JOIN NM_CONTR C ON D.COD_EMPL = C.COD_EMPL AND C.NRO_CONT = D.NRO_CONT
LEFT JOIN GN_CCOST T ON C.COD_AREA = T.COD_CCOS
LEFT JOIN BI_EMPLE B ON C.COD_EMPL = B.COD_EMPL
LEFT JOIN BI_CARGO K ON C.COD_CARG = K.COD_CARG
where cod_vari = 'BON_BASE'