--INFORME VISMAR AUSENTISMOS Y VACACIONES*

SELECT U.NOM_AREA, A.COD_EMPL, B.NOM_EMPL, B.APE_EMPL, A.COD_CONC, A.COD_MAUS, A.TIP_AUSE, A.FEC_DESD, A.FEC_HAST, A.CAN_AUSE, C.NOM_CONC, M.NOM_MAUS, A.OBS_ERVA, A.ACT_HORA FECHA_EDICION
FROM NM_AUSEN A
LEFT JOIN BI_EMPLE B ON A.COD_EMPL = B.COD_EMPL
LEFT JOIN NM_CONCE C ON A.COD_CONC = C.COD_CONC
LEFT JOIN NM_CONTR D ON A.COD_EMPL = D.COD_EMPL
LEFT JOIN SO_AREAS U ON D.COD_AREA = U.COD_AREA
LEFT JOIN NM_MAUSE M ON A.COD_MAUS = M.COD_MAUS
WHERE (C.COD_CONC <> 1061 AND A.FEC_DESD >='25/04/2023' AND A.CAN_AUSE >3) --Rango licencias
OR ((C.COD_CONC = 1061 AND A.FEC_DESD BETWEEN '01/05/2023' AND '31/05/2023') OR (C.COD_CONC = 1061 AND A.ACT_HORA >='01/04/2023')) AND D.IND_ACTI = 'A'  --Rango de fechas vacaciones
OR (C.COD_CONC <> 1061 AND A.ACT_HORA >='25/01/2023' /*ESTA FECHA ES PARA FECHA EN LA QUE SE INTRODUJO LA NOVEDAD EN EL SISTEMA*/ 
AND A.CAN_AUSE >3 AND A.FEC_HAST >= '25/04/2023') --Rango licencias


*INFORME VISMAR RETIRADOS*

SELECT U.NOM_AREA, C.COD_EMPL, B.NOM_EMPL, B.APE_EMPL, C.FEC_INGR, C.FEC_DEJA, K.NOM_CARG, M.NOM_MDEJ
FROM NM_CONTR C
LEFT JOIN BI_EMPLE B ON C.COD_EMPL = B.COD_EMPL
LEFT JOIN SO_AREAS U ON C.COD_AREA = U.COD_AREA
LEFT JOIN NM_MDEJA M ON C.COD_MDEJ = M.COD_MDEJ
LEFT JOIN BI_CARGO K ON C.COD_CARG = K.COD_CARG
WHERE C.IND_ACTI IN('R','I') AND C.FEC_DEJA >= '25/04/2023' --Rango retirados

