-- PUEDE SERVIR PARA CHIP

SELECT N.COD_CARG,N.COD_CONC,NM_NCRCC.COD_CUEN,NM_NCMCO.NOM_CUEN,NM_CONCE.TIP_CONC,SUM(n.VAL_ACUM) DEV_ENGA                                                    
FROM
NM_ACUMU N,
NM_CONCE,
NM_NCRCC,
--GN_CCOST,
NM_NCMCO
WHERE
N.COD_EMPR=NM_CONCE.COD_EMPR AND
N.COD_EMPR=NM_NCRCC.COD_EMPR AND
NM_NCRCC.COD_EMPR=NM_NCMCO.COD_EMPR AND
N.COD_CONC=NM_CONCE.COD_CONC AND
N.COD_CONC=NM_NCRCC.COD_CONC AND
NM_NCRCC.COD_CUEN=NM_NCMCO.COD_CUEN AND
--NM_NCRCC.CAM_RELA=N.COD_CCOS AND
--GN_CCOST.COD_CCOS=NM_NCRCC.CAM_RELA AND 
--GN_CCOST.COD_CCOS=N.COD_CCOS AND    
N.FEC_ACUM >= '01/02/2022' AND
N.FEC_ACUM <= '28/02/2022'  
-- N.STR_RES3  in('N01102021') 
-- NM_NCRCC.COD_CUEN LIKE '%A-%' AND
--NM_CONCE.TIP_CONC='I' 
GROUP BY N.COD_CARG,N.COD_CONC,NM_NCRCC.COD_CUEN,NM_NCMCO.NOM_CUEN,NM_CONCE.TIP_CONC
ORDER BY N.COD_CARG,N.COD_CONC,NM_NCRCC.COD_CUEN


SELECT IND_LABO, TIP_DIAS, act_hora FROM GN_CALEN  WHERE COD_EMPR =311 AND COD_TIPC = 1
 AND INI_TIPC = 'BI' AND FEC_CALE ='03-04-2023'