SELECT P.NRO_CONT, P.COD_EMPL, B.NOM_EMPL, B.APE_EMPL, P.COD_CONC, X.NOM_CONC, C.NOM_CCOS
FROM NM_PRENO P
LEFT JOIN BI_EMPLE B ON P.COD_EMPL = B.COD_EMPL
LEFT JOIN GN_CCOST C ON P.COD_CCOS = C.COD_CCOS
LEFT JOIN NM_CONCE X ON P.COD_CONC = X.COD_CONC
WHERE P.COD_CARG IS NULL OR P.COD_CARG < 1