SELECT T.NOM_AREA, C.COD_EMPL, B.NOM_EMPL, B.APE_EMPL, C.NRO_CONT, C.FEC_INGR, C.COD_CARG, E.NOM_ESCA, C.IND_ACTI, D.COD_VARI, 

CASE
    WHEN (SELECT to_DATE(sysdate) FROM dual) >= '31/12/2022' THEN
        TO_CHAR('31/12/2022')
END FECHA_CORTE

FROM NM_CONTR C
LEFT JOIN BI_EMPLE B ON C.COD_EMPL = B.COD_EMPL
LEFT JOIN SO_AREAS T ON C.COD_AREA = T.COD_AREA
LEFT JOIN NM_ESCAR E ON C.COD_ESCA = E.COD_ESCA
LEFT JOIN NM_DECON D ON C.COD_EMPL = D.COD_EMPL AND C.NRO_CONT = D.NRO_CONT AND D.COD_VARI = 'BON_BASE'
WHERE C.IND_ACTI IN('A','R') AND C.FEC_INGR <='31/12/2022'
ORDER BY C.COD_EMPL